### ISSUE TITLE
changes in ccnl-ext-mgmt.c doesn't apply after first make

### ISSUE THREAD

**Issue by Maxilicious** [cn-uofbasel/ccn-lite#94]
Hi,

We're trying to implement ccnl_mgmt_prefixunreg(ccnl, orig, prefix, from), and we are encountering an issue.

If we Make the project, everything runs as intended. If we then write changes in the ccnl-ext-mgmt.c file, and do a Make clean all, the changes we've made isn't reflected when the ccnl-lite-ctrl is ran. 

Example: 

**Scenario 1:**
We run 
_ccn-lite-ctrl -x /tmp/mgmt-relay-a.sock prefixreg /ndn $FACEID ndn2013_  
and get output
**<CONTENTOBJ>
    <NAME>
        <COMPONENT>ccnx</COMPONENT>
        <COMPONENT></COMPONENT>
        <COMPONENT>prefixreg</COMPONENT>
    </NAME>
    <CONTENT>
        <PREFIX>
            <ACTION>prefixreg cmd worked</ACTION>
            <NAME>/ndn</NAME>
            <FACEID>70</FACEID>
            <SUITE>6</SUITE>
        </PREFIX>
    </CONTENT>
</CONTENTOBJ>**

**Scenario 2:**
We change the 
_cp = "prefixreg cmd worked";_ // in ccnl-ext-mgmt.c
to
_cp = "Change in string";_ //// in ccnl-ext-mgmt.c
run Make clean all and then 
**ccn-lite-ctrl -x /tmp/mgmt-relay-a.sock prefixreg /ndn $FACEID ndn2013**  
and the output is still
**<CONTENTOBJ>
    <NAME>
        <COMPONENT>ccnx</COMPONENT>
        <COMPONENT></COMPONENT>
        <COMPONENT>prefixreg</COMPONENT>
    </NAME>
    <CONTENT>
        <PREFIX>
            <ACTION>prefixreg cmd worked</ACTION>
            <NAME>/ndn</NAME>
            <FACEID>70</FACEID>
            <SUITE>6</SUITE>
        </PREFIX>
    </CONTENT>
</CONTENTOBJ>**

So changes we make in the ccnl-ext-mgmt.c isn't reflected during runtime. Altough if we do not Make project after we cloned it, do our editing, and then Make, our changes are reflected. So somehow it appears that the old code is run even after a Make clean all.

**Comment by blacksheeep** [comment]
Hi,
Thanks for reporting.

It seems, we have an error in our build system, so that sometimes not everything changed is rebuild, when running "make all".

When calling "make clean all", all existing binaries are deleted, thus the complete project is rebuild. I would recommend to always call "make clean all" for now. 
I could not reproduce any case, where old code is executed, after calling "make clean all".
(except for ccn-lite-flic and ccn-lite-repo256, which was missing in the makefile. i fixed this).

**Comment by Maxilicious** [comment]
Hi,

We always run "make clean all", and the problem persists, so there appears to be some binary that is still present (Somehow, it's all very strange). You were'nt able to reproduce scenario 2?

/Max

**Comment by blacksheeep** [comment]
Hi,
for me it recompiling works correct. 

I changed the mgmt.c file on this position:
<img width="579" alt="screenshot 2016-09-13 20 00 55" src="https://cloud.githubusercontent.com/assets/3641597/18485382/dfaed048-79ec-11e6-8819-56436429d26c.png">

And after recompiling I get this reply message:
<img width="500" alt="screenshot 2016-09-13 20 02 32" src="https://cloud.githubusercontent.com/assets/3641597/18485433/0ad2c13a-79ed-11e6-9017-d1c0ffc766bd.png">

Can you ensure, that you closed all running instances of ccn-lite before recompiling?

I'm using MacOS El Capitan, with LLVM version 7.3.0 and GNU Make 3.81.
Could you provide me information about your system, so that I can setup a similar system?

**Comment by mfrey** [comment]
Probably want to mark this as 'won't fix' and close it since you changed the build system anyway?

**Comment by blacksheeep** [comment]
Closed, since build system changed
